### ISSUE TITLE
command 'extension.algorithm-contest-scrapper' not found

### ISSUE THREAD

**Issue by kamiltxyz** [tjovicic/algorithm-contest-scrapper#1]
This error pops up when I try to user this extension on clean Ubuntu 18.04 installation. Any Idea how to get it working?

**Comment by tjovicic** [comment]
I'm sorry for that. Going to check it out in a few hours

**Comment by tjovicic** [comment]
The error has been fixed, please download extension version 0.0.2. 

Thanks for the feedback :)
